server:
  port: 10010
logging:
  level:
    cn.akfang.snow: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters:
            - RewritePath=/user/(?<segment>.*), //$\{segment}
#        - id: order-service
#          uri: lb://courseservice
#          predicates:
#            - Path=/course/**
#      default-filters:
#        - AddRequestHeader=
