server:
  port: 10010
logging:
  level:
    cn.akfang.snow: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
    gateway:
      routes:
        - id: clazz-service # 路由标示，必须唯一
          uri: lb://clazzservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/clazz/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters:
            - RewritePath=/clazz/(?<segment>.*), //$\{segment}

        - id: course-service # 路由标示，必须唯一
          uri: lb://courseservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/course/** # 路径断言，判断路径是否是以/course开头，如果是则符合
          filters:
            - RewritePath=/course/(?<segment>.*), //$\{segment}

        - id: exam-service # 路由标示，必须唯一
          uri: lb://examservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/exam/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters:
            - RewritePath=/exam/(?<segment>.*), //$\{segment}

        - id: homework-service # 路由标示，必须唯一
          uri: lb://homeworkservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/homework/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters:
            - RewritePath=/homework/(?<segment>.*), //$\{segment}

        - id: message-service # 路由标示，必须唯一
          uri: lb://messageservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/message/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters:
            - RewritePath=/message/(?<segment>.*), //$\{segment}

        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters:
            - RewritePath=/user/(?<segment>.*), //$\{segment}